### ISSUE TITLE
The charm memory usage, OOM killed

### ISSUE THREAD

**Issue by yanksyoon** [canonical/mysql-operator#299]
## Steps to reproduce

We can't confirm this is 100% reproducible yet, but observed this in a production environment under the conditions described.

1. deploy mysql charm on juju with default constraints (`arch=amd64 cpu=2 mem=4096M`) with 3 units
2. add subordinate charms: `landscape-client`, `telegraf`, `ubuntu_advantage`
3. deploy wordpress-k8s and relate to charm

## Expected behavior
The `mysql` charm applications to be stable.

## Actual behavior
The application OOMs and dies

## Versions

Operating system: Ubuntu 20.04.6 LTS

Juju CLI: 2.9.44-ubuntu-amd64

Juju agent: 2.9.44

Charm revision: 169

LXD: N/A

## Log output

`Openstack console log show` output: 

```
[1464988.945046] Out of memory: Killed process 19798 (mysqld) total-vm:7419460kB, anon-rss:3191380kB, file-rss:0kB, shmem-rss:0kB, UID:584788 pgtables:6916kB oom_score_adj:0
```

## Additional context

This seems to have happened after the charm leadership change.
Raising this ticket to raise awareness of the charm's resource usage, please let me know for additional logs you might need!

**Comment by paulomach** [comment]
@yanksyoon is the unit running only the mysql charm?

**Comment by taurus-forever** [comment]
Dear @yanksyoon , the reported issue triggered a lot of questions from my side, let's separate them:

1. OOM is just killing the biggest RAM consumer => mysqld. Expected when no RAM left inside charm.
2. The current expectation is: the whole unit RAM is for MySQL (see below different 'Profiles'[1]).
3. The tested revision 169 doesn't have [the fix](https://github.com/canonical/mysql-operator/pull/253) to include `group_replication_message_cache_size` into RAM calculation. Please re-try with the latest `8.0/edge` revision.
4. Let's discuss charms you are subordinating into: 

- `telegraf` - is it for monitoring? Note: our charm supports [COS monitoring](https://charmhub.io/mysql/docs/h-enable-monitoring), no need for telegraf inside.
- `landscape-client` - is it for gathering statistic OR to control/upgrade workload (apt, snaps, ...)? Note: `landscape-server` must NOT update anything inside the charm (c) @delgod . The integration with Landscape server must be an epic for the next sprint to declare it.
- `ubuntu-advantage` - I am not sure about the purpose of this charm. Ubuntu PRO? FIPS? Please share more details here.

_Profiles[1]_.
The latest revisions of our charm supports two deployment profiles:
 - testing:  `juju deploy mysql --profile testing`. See the limits [here](https://github.com/canonical/mysql-operator/blob/6910ff05b5da15f648c28fbbb7159c478356d9ba/src/mysql_vm_helpers.py#L181). TL;DR: use as small RAM as possible for MySQL. Useful for testing and CI/CD.
 - default:  `juju deploy mysql`. [Here](https://github.com/canonical/mysql-operator/blob/93b85dc9c0fa9dc4177e65c92913618b7c63f128/lib/charms/mysql/v0/mysql.py#L1962) is RAM consumption calculations. TL;DR: 75% RAM is for MySQL. Unfortunately MySQL requires the proper RAM configuration on bootstrap to provide the best performance => we have to set some limits. The current one is 75% of unit RAM. The rest 25% should be good enough for subordinated activities, otherwise => OOM (see the point 1. above).

I hope it brings more lite to your findings. Please share your re-try results with revision 172+ (better latest from '8.0/edge'). Tnx!

**Comment by yanksyoon** [comment]
@taurus-forever Thanks for the insights!

Regarding 4, I believe the subordinate charms are reused code for terraform deployment for machine charms, for backwards compatible monitoring that we currently have. I will look into moving observability to COS.

I will try running the profiles with staging deployment of the mysql charm on revision 172+, thank you for the detailed instructions!

**Comment by mthaddon** [comment]
@taurus-forever landscape-client provides package updates, and ubuntu-advantage enables pro which ensures package updates on a wider range of packages, as well as enabling live kernel patching. Telegraf provides host level metrics as we don't (yet) have a centralised COS instance to relate to here.

**Comment by taurus-forever** [comment]
@mthaddon thank you for insides! All matches my understanding.

In fact we need to schedule integration with `landscape-server`.
**Important**: [the legacy mysql charm](https://charmhub.io/mysql/docs/e-legacy-charm) relied on `landscape` to upgrade mysql. The modern Charmed MySQL upgrades entire cluster internally. Moreover, landscape must NOT upgrade snap `charmed-mysql` => integration is necessary. CC @delgod , Mohamed.

re: `telegraf` - IMHO, unnecessary. AFAIK, `grafana-agent` exports host level metrics already (using [node_exporter](https://grafana.com/grafana/dashboards/1860-node-exporter-full/)).

re: `ubuntu-advantage` - IMHO, absolutely necessary. We need to schedule testing with Ubuntu PRO + livepatch. CC @delgod , Mohamed.

What do you think?

**Comment by mthaddon** [comment]
I'd argue that both landscape-client and ubuntu-advantage _are_ needed, to upgrade resources not managed by the charm directly (e.g. system packages, kernel, etc.). We really can't run production services without those without being exposed to significant security risks.

**Comment by taurus-forever** [comment]
@mthaddon I am with you. My point: it was never in requirements for the previous sprints.
It must be fully tested internally and covered with integration tests to avoid regression => contact Mohamed to include in the next sprint.

**Comment by mthaddon** [comment]
Btw, the landscape-client charm doesn't upgrade snaps, only packages.

**Comment by gregory-schiano** [comment]
It would be interesting to see the memory footprint of the 3 subordinated charms, if most of the memory is taken by telegraf, we know `grafana-agent` is the way to go (but still have to manage some legacy things). If that's either landscape or ubuntu-advantage, then we might still have issues with mysql

**Comment by taurus-forever** [comment]
I have reproduced the setup locally:

1) RAM is used by running service + a lot of resources used on subordinate installation stage too (`juju refresh telegraf` might OOM mysqld): cython is compiled from pip in a moment of telegraf installation/refresh.
2) AFAIK, telegraf will eat RAM if cannot push metrics to InfluxDB (networking issue).
3) MySQL RAM consumption changes over the time and cannot really be limited in full. There is a chance for MySQL to eat all the RAM+SWAP for crazy use cases.

Anyway:
* The proposal to improve Juju to assume HW resources requirements: https://bugs.launchpad.net/juju/+bug/2032918 (rejected)
* We will discuss and improve the default MySQL RAM usage to give users ability to limit mysqld buffers/caches manually.
* I see the benefits and need to use `landscape-client`+`ubuntu-advantage/livepatch`, but this should be processed properly inside the team, to test such setups and catch all possible issues in our CI/CD.

**Comment by yanksyoon** [comment]
Hello @taurus-forever, would you have a timeline on when the fix might land on `edge`?

**Comment by paulomach** [comment]
@yanksyoon we do have greater granularity with `profile` and [`profile-limit-memory`](https://charmhub.io/mysql-k8s/configure#profile-limit-memory) for a while now.
Let me know if I can close this issue

**Comment by yanksyoon** [comment]
@paulomach We've currently deployed w/ `edge` rev 192, and currently haven't had OOMs so far - if it happens again i'll issue an upgrade to `stable/196` with `profile=production` settings - I think it's fine to close it for now.
One question though, is there an upgrade path from edge/192 to stable/196 (`juju refresh`)? or is it required to do a db migration?

**Comment by paulomach** [comment]
@yanksyoon , there's a path using the in-place upgrades feature (available in rev192). Check the [docs here](https://charmhub.io/mysql/docs/h-upgrade-minor).
